### ISSUE TITLE
Incompatible with more recent Forge versions?

### ISSUE THREAD

**Issue by katubug** [KillerMapper/EmbellishCraft#22]
Hi! I was working on a new modlist for 1.15.2, using EmbellishCraft 2.2.1.0 and MapperBase 1.1.1.0.

When using the most recent Forge version on Twitch, 31.2.9 (or 31.2.8, which is the lowest required version for another mod I'm using), the game fails to complete loading. Here is my latest.log: https://pastebin.com/FsxafuqP

I do not have this issue on Forge 31.2.27. I just checked and saw that the most recent update of EmbellishCraft was compatible with 31.2.21, so it's very likely that you're aware of this and working on catching up.

If so, feel free to just close this, and I'll wait for an update. :) Thanks very much for your time! I look forward to using the mod! :D

**Comment by MapperTV** [comment]
Forge apparently did changes between the latest Release Build (31.2.0) and some newer version I don't know exactly. I used 31.2.21 to make the latest update and used the new code provided by Forge as the old one was deprecated.

31.2.9 is already old. When I write this there is already 31.2.27 available. You have to use newer Forge versions to avoid the crash, mods using older versions should still work otherwise Forge would have a new Release Build. If some mods can't work then they need to be updated.

**Comment by katubug** [comment]
Oh, then this was user error/issue with Twitch launcher (shock! Lol). The launcher gives 31.2.27 as an initial install option but if you try to update, it only goes up to 3.2.9. The user error is my brain going "well 0.9 is larger fractionally than 0.27 therefore this must be the newer release, which is why it's the top option."

I should learn not to assume that Twitch has done something correctly. My apologies for the false alarm!
